### ISSUE TITLE
[enhancement]capability to pass metadata field to keyfactor

### ISSUE THREAD

**Issue by char-iot** [Keyfactor/command-cert-manager-issuer#10]
for example:

![image](https://github.com/Keyfactor/command-cert-manager-issuer/assets/16464579/e14f65f6-4e9e-4247-8fa6-2599c77b93e7)

**Comment by m8rmclaren** [comment]
Hello! Thank you for submitting this issue. Trying to understand the need better; do you have any ideas as to how custom fields such as `ResponsibleTeam` would be populated by the signer? I have the following idea, and I'd like your feedback:

Add custom logic to [`commandSigner.Sign()`](https://github.com/Keyfactor/command-cert-manager-issuer/blob/09ff15488e1579410260d324ab3f3a98d2b78a92/internal/issuer/signer/signer.go#L152C27-L152C27) to listen for custom K8s annotations (that [aren't already used for overriding defaults](https://github.com/Keyfactor/command-cert-manager-issuer/tree/main#annotation-overrides-for-issuer-and-clusterissuer-resources)) on `Certificate.cert-manager.io/v1` objects that map to Command Metadata `Name` fields.

For example:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    command-issuer.keyfactor.com/ResponsibleTeam: "theResponsibleTeam@example.com"
```

If you have another idea, please feel free to let me know!
